### ISSUE TITLE
hitchwiki in czech

### ISSUE THREAD

**Issue by guaka** [Hitchwiki/hitchwiki#42]
As requested by Daniel

**Comment by guaka** [comment]
https://hitchwiki.org/cz/
`[2939c0fc77723138de30fc48] 2019-07-18 20:55:43: Fatal exception of type MWException`

**Comment by zrthstr** [comment]
shall we get rid of the CZ wiki?

**Comment by guaka** [comment]
I'm not sure what was there. If people put in an effort to build this we should try to reconstruct it.

I'll check with my Czech friend ;)

**Comment by mrkvon** [comment]
@zrthstr @guaka 
regarding the Czech wiki, I have no idea what is there either. Does @matyasbach know?

Anyways, I suggest [investigating the bug further](https://stackoverflow.com/questions/17824295/fatal-exception-of-type-mwexception). Otherwise we may be [throwing the baby out with the bathwater](https://en.wikipedia.org/wiki/Don%27t_throw_the_baby_out_with_the_bathwater).
