### ISSUE TITLE
Figure out statistics from waiting times

### ISSUE THREAD

**Issue by simison** [Hitchwiki/hitchwiki#62]
- [x] How big percentage of spots have 1 waiting time, 2 times, 3 times, etc?
- [x] Figure out how many waiting times are required for calculating median
- [x] How big percentage of all spots are ok for calculating median?
- [ ] What would be good and accurate ways of presenting waiting time in one line in different cases? Average? "5min—45min"? Something else?

**Comment by Simsadz** [comment]
![count_waittimes](https://cloud.githubusercontent.com/assets/9862538/5606737/9a8b9e3a-9445-11e4-9d9d-4e2d0903b8c4.png)
65% of all spots have only 1 waiting time entered, while 16% have 2 waiting times! So for all those 81% of spots, of course, showing average or median in order to summarize waiting times is the same.  
For the remaining 18% (1805) of spots: showing median instead of average would avoid the effect of outliers ( e.g. one person waited 20 hours and then average for this spot becomes much higher).
On the other hand, the median wouldn’t show the randomness of the place ( is it always very easy to hitch there or is it sometimes difficult etc.) . To see this randomness, such one line graphs for each spot (instead of average now) would be nice. Instead of legend there could be annotations under the graph:
![wait_times_distribution](https://cloud.githubusercontent.com/assets/9862538/5606748/6ca6df24-9446-11e4-9fe2-5973321715cd.png)
