### ISSUE TITLE
Special pages

### ISSUE THREAD

**Issue by Kundrt** [Hitchwiki/hitchwiki#68]
http://hitchwiki.org/en/Special:SpecialPages - useful link almost at the end of hitchwiki sidebar doesn't work any more. There was list of special pages for checking double redirects, uncategorized pages and many others.

**Comment by simison** [comment]
There's a bug coming up from WP+MW setup —it's either logins working or special pages working.

We're in the makes of new HW right now so this will get fixed with that; I don't feel like spending time to fix old codebase, sorry. 

Redirects page: http://hitchwiki.org/en/Special:DoubleRedirects

Would you need some other pages?

**Comment by Kundrt** [comment]
No thanks, I can find the pages. Looking forward for new HW :)

**Comment by simison** [comment]
Ye! A week or two more and there should be a demo for testing. :-)

**Comment by simison** [comment]
This are working again now that I BuddyPress Wordpress login connection.
